project:
  type: website

website:
  title: "Jhodany Parejas Gonzales"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - ANTECEDENTES.qmd
      - METODOLOGIA.qmd
      - REFERENCIAS.qmd
    right:
      - icon: github
        href: https://github.com/jhodany-07/tesis-1.git  
      - icon: linkedin
        href: https://linkedin.com
      - icon: Facebook
        href: https://facebook.com 
      
format:
  html:
    theme: [cosmo, styles.scss]

