---
title: "ANTECEDENTES"
---

{{< lipsum1 >}}

Entre los insectos parasitoides que han sido importados intencionalmente durante décadas (Segoli et al., 2023), destacan especialmente los parasitoides del Orden Hymenoptera y Diptera, un taxón complejo y diverso que incluye especies que ejercen control biológico sobre plagas, contribuyendo a la sustentabilidad de los agroecosistemas (Collantes González & Rodríguez Berrio, 2017). Hace más de 200 años surgió un estilo de vida parasitoide en el antepasado de los Orussidae y Apocrita (Cusumano & Fatouros, 2023), lo que permitió que los himenópteros se diversificaran para parasitar una gran variedad de huéspedes, siendo la primera vez que se usó el término “parasitoide” en 1913 en una publicación de Reuter, Buch y Buch (Löhr et al., 1913).
En diversas regiones del mundo se han realizado estudios sobre la diversidad y abundancia de parasitoides en maíz, reportándose familias como Braconidae (Blanco & Riverón, 2014), Ichneumonidae en México (Cancino et al., 2014); Bethylidae y Tachinidae, en Paraguay (Cabral et al., 2016), Dryinidae en Argentina (Virla & Olmi, 2007); Chalcididae, Sarcophagidae y Platygastridae, en Ecuador (Chirinos et al., 2024). Siendo considerados como importantes agentes de biocontrol de plagas como el saltahojas del maíz, Dalbulus maidis; chicharrita del maíz, Dalbulus maidis, Frankliniella occidentalis; Gusano elotero, Helicoverpa zea;, Euxesta stigmatias (Trejo et al., 2019), Elasmopalpus lignosellus, Diatraea saccharalis y Spodoptera frugierda. Siendo esta ultima una plagas de importancia agronómica y económica a nivel mundial (Calvo, 2014). 
(Ochoa et al., 2003), en su publicación “Parasitoides y Parásitos de Spodoptera Frugiperda (Lepidoptera: Noctuidae) en las Américas y la Cuenca del Caribe: Un Inventario”, identificaron diversos parasitoides asociados a Spodoptera frugiperda, siendo el maíz el cultivo donde más frecuentemente se recolectaron. Estos parasitoides incluyen especies como Diapetimorpha introita (parasitoide pupal más importante), C. insulares, Chelonus sp. y Euplectrus platyhypenae, en América del Norte; C. insulares, en América Central; y Archytas incertus (Macq.), A. marmoratus (Tns.), C. insularis y Meteorus laphygmae (Viereck), en América del Sur.  
Sharanabasappa et al., (2019), en un estudio realizado en el sur de la India, identificaron cinco especies de parasitoides larvarios asociados a Spodoptera frugiperda. Entre ellas se encuentran Campoletis chlorideae y Exorista sorbillans, así como tres especies nuevas que no habían sido previamente descritas como parasitoides de S. frugiperda: Coccygidium melleum, Eriborus sp. y Odontepyris sp., pertenecientes a las familias Braconidae, Ichneumonidae y Bethylidae, respectivamente. En cambio, en el Este se han descrito dos parasitoides de huevos y ocho parasitoides de larvas de S. frugiperda. Microplitis manilae fue descrito como especie de parasitoide larval más abundante, y Telenomus cf. remus como especie dominante de parasitoide de huevos (Pal et al., 2024). 
Así mismo, Lestari et al., (2024) identificaron cuatro especies de parasitoides asociadas a Spodoptera frugiperda en Indonesia: Senometopia illota, Eriborus sp., Chelonus formosanus y Drino (Palexorista) sp.. Entre estas, S. illota y el género Eriborus sp. son registros recientes como parasitoides de S. frugiperda a nivel global. 
En Perú, Ochoa et al., (2003) identificaron diversas especies de parasitoides asociadas a Spodoptera frugiperda, tales como Ophion sp., Trachysphyrus cleonis, Netelia sp., Campoletis curvicauda, Meteorus sp., Cotesia (Apanteles) sp., Chelonus sp., Gonia pacifica, Eucelatoria australis y Archytas marmoratus. Estos registros contribuyen al conocimiento de la diversidad de parasitoides en el país y resaltan su potencial en programas de control biológico contra esta plaga de importancia agrícola. 
Estudios en Capote y Ferreñafe reportaron hasta un 40% de parasitismo natural en larvas en parcelas sin plaguicidas, y cerca del 27% de parasitismo en huevos en zonas con aplicación de plaguicidas.  Encontrando parasitoides como Archytas sp, Winthemia sp, Chelonus sp, Eiphosoma sp, Campoletis sp, Ophion sp, Eiphosoma sp, Cotesia sp. y Telenomus sp. (Rodríguez & Castro, 2021). Mientras que en Mollebamba, Acobamba Quispe, (2022), Huancavelica reportó a Aphydius matricariae. 
En la región Amazonas se cultiva maíz en diferentes zonas agroecológicas, pero existen pocos estudios sobre la fauna de parasitoides que podrían contribuir al control natural de plagas que afectan este cultivo. Por lo tanto, es necesario realizar un estudio detallado que permita identificar taxonómicamente las especies de parasitoides presentes, utilizando muestreos de campo y claves taxonómicas, y así elaborar un listado preliminar que sirva de base para futuras investigaciones y estrategias de manejo integrado de plagas en el cultivo de maíz en la región.
## HIPOTESIS 
Se espera que los parasitoides identificados a partir de las muestras de campo pertenecen a familias reportadas previamente en otras regiones de Perú y el mundo, pero que existirán especies nuevas o registros locales que enriquecerán el listado preliminar de parasitoides asociados a Spodoptera frugiperda en el cultivo de maíz en la región Amazonas. 
