---
title: "REFERENCIAS BIBLIOGRAFICAS"
---

Blanco, J. M. C., & Riverón, A. Z. (2014). Biodiversidad de Braconidae (Hymenoptera: Ichneumonoidea) en México. Revista Mexicana de Biodiversidad, 85, 372-378. https://doi.org/10.7550/rmb.32000
Broad, G. (2015). Wings absent or reduced:
Cabral, C., Gómez, A., Cardenas, R., & Armoa, K. (2016). Identificación de parasitoides en el cultivo de maíz (Zea mays) en Canindeyú e Itapúa. https://www.cabi.org/wp-content/uploads/Cabral-2016-Parasitoids-in-corn.pdf
Calvo, W. J. (2014). MANEJO INTEGRADO DEL CULTIVO Y DE LAS PLAGAS DEL MAÍZ. https://repositorio.inia.gob.pe/server/api/core/bitstreams/6e844871-80f9-4ee6-99e9-83964a2951bc/content
Cancino, E. R., Kasparyan, D. R., Moreno, A. G., Khalaim, A. I., & Blanco, J. M. C. (2014). Biodiversidad de Ichneumonidae (Hymenoptera) en México. Revista Mexicana de Biodiversidad, 85, 385-391. https://doi.org/10.7550/rmb.32448
Chirinos, D. T., Sánchez-Mora, F., Zambrano, F., Castro-Olaya, J., Vasconez, G., Cedeño, G., Pin, K., Zambrano, J., Suarez-Navarrete, V., Proaño, V., Mera-Macias, J., & Vasquez, C. (2024). Entomofauna Associated with Corn Cultivation and Damage Caused by Some Pests According to the Planting Season on the Ecuadorian Coast. Agronomy, 14(4), 748. https://doi.org/10.3390/agronomy14040748
Collantes González, R., & Rodríguez Berrio, A. (2017). Diversidad de avispas parasitoides (Hymenoptera) en agroecosistemas de palto (Persea americana Mill.) y mandarina (Citrus spp.) en Cañete, Lima, Perú. APORTE SANTIAGUINO, 8(2), 207. https://doi.org/10.32911/as.2015.v8.n2.226
Cusumano, A., & Fatouros, N. E. (2023). Editorial overview: Parasites/parasitoids/biological control (2023) Understanding parasitoid ecology and evolution to advance biological control programs. Current Opinion in Insect Science, 58, 101050. https://doi.org/10.1016/j.cois.2023.101050
Gupta, A., Lalitha, Y., Varshney, R., Shylesha, A., & Van, C. (2019). Chelonus formosanus Sonan (Hymenoptera: Braconidae) an egg-larval parasitoid of the invasive pest Spodoptera frugiperda (J. E. Smith) (Lepidoptera: Noctuidae) amenable to laboratory mass production in India. Journal of Entomology and Zoology Studies.
Lestari, P., Fitriana, Y., Suharjo, R., Swibawa, I. G., Utomo, S. D., & Andrianto, E. (2024). Nuevos parasitoides de Spodoptera frugiperda en la provincia de Lampung, Indonesia. Journal of Asia-Pacific Biodiversity, 17(4), 631-643. https://doi.org/10.1016/j.japb.2024.02.005
Löhr, B., Niño, M. F. D., Manzano, M. R., Vásquez, C. A. N., Gómez-Jiménez, M. I., Carabalí, A., Vargas, G., Kondo, T., & Pardey, A. E. B. (1913). Use of parasitoids in insect biological control in Colombia. . ., 489.
Ochoa, J. M., Carpenter, J. E., Heinrichs, E. A., & Foster, J. E. (2003). PARASITOIDS AND PARASITES OF SPODOPTERA FRUGIPERDA (LEPIDOPTERA: NOCTUIDAE) IN THE AMERICAS AND CARIBBEAN BASIN: AN INVENTORY. Florida Entomologist, 86(3), 254-289. https://doi.org/10.1653/0015-4040(2003)086[0254:PAPOSF]2.0.CO;2
Pal, S., Bhattacharya, S., Dhar, T., Gupta, A., Ghosh, A., Debnath, S., Gangavarapu, N., Pati, P., Chaudhuri, N., Chatterjee, H., Senapati, S. K., Bhattacharya, P. M., Gathala, M. K., & Laing, A. M. (2024). Hymenopteran parasitoid complex and fall armyworm: A case study in eastern India. Scientific Reports, 14(1), 4029. https://doi.org/10.1038/s41598-024-54342-z
Quispe, S. (2022). Evaluación y Monitoreo de los Enemigos Naturales en el Cultivo de Maíz (Zea mayz) en Condiciones de Mollebamba– Acobamba. https://apirepositorio.unh.edu.pe/server/api/core/bitstreams/a69e0233-9db2-4b24-ad80-e4e67d7673da/content
Rodríguez, K., & Castro, Lady. (2021). Insectos parasitoides asociados al control de Spodoptera frugiperda en maíz amarillo duro (Zea mays) en 3 zonas maiceras de la región Lambayeque [UNIVERSIDAD NACIONAL PEDRO RUIZ GALLO]. https://hdl.handle.net/20.500.12893/13383
Segoli, M., Abram, P. K., Ellers, J., Greenbaum, G., Hardy, I. C. W., Heimpel, G. E., Keasar, T., Ode, P. J., Sadeh, A., & Wajnberg, E. (2023). Trait-based approaches to predicting biological control success: Challenges and prospects. Trends in Ecology & Evolution, 38(9), 802-811. https://doi.org/10.1016/j.tree.2023.04.008
Sharanabasappa, Kalleshwaraswamy, C. M., Poorani, J., Maruthi, M. S., Pavithra, H. B., & Diraviam, J. (2019). Natural Enemies of Spodoptera frugiperda (J. E. Smith) (Lepidoptera: Noctuidae), a Recent Invasive Pest on Maize in South India. Florida Entomologist, 102(3), 619-623. https://doi.org/10.1653/024.102.0335
Trejo, A. H., Estrada Drouaillet, B., Rodríguez-Herrera, R., García Giron, J. M., Patiño-Arellano, S. A., Osorio-Hernández, E., Hernández-Trejo, A., Estrada Drouaillet, B., Rodríguez-Herrera, R., García Giron, J. M., Patiño-Arellano, S. A., & Osorio-Hernández, E. (2019). Importancia del control biológico de plagas en maíz (Zea mays L.). Revista mexicana de ciencias agrícolas, 10(4), 803-813. https://doi.org/10.29312/remexca.v10i4.1665
Tschorsnig, H.-P., & Herting, B. (2001). The Tachinids (Diptera: Tachinidae) of Central Europe: Identification Keys for the Species and Data on Distribution and Ecology.
Virla, E. G., & Olmi, M. (2007). Dryinidae (Hymenoptera: Chrysidoidea) parasitoids of the corn leafhopper, Dalbulus maidis (Delong & Wolcott) (Hemiptera: Cicadellidae), in Argentina, with description of the male of Gonatopus moyaraygozai Olmi. Interciencia, 32(12), 847-849.

