---
title: "Problema de Investigación"
format: html
editor: visual
---

En el Perú, el maíz es un cultivo de gran importancia económica y alimentaria. Según datos del Ministerio de Desarrollo Agrario y Riego (MIDAGRI, 2024), durante el año 2024 se registró una producción nacional de 113,385 toneladas de maíz, incluyendo tanto el maíz amarillo duro como el maíz amiláceo. De este total, el departamento de Amazonas aportó aproximadamente el 3%, lo que equivale a 3,271 toneladas, de acuerdo con el reporte del Sistema Integrado de Estadística Agraria (SiEA). Esta cifra refleja la relevancia del cultivo en la región, así como su contribución a la seguridad alimentaria y la economía agrícola del país.

Debido a su importancia económica, el cultivo de maíz enfrenta grandes desafíos en su manejo, especialmente en el ámbito fitosanitario. En los últimos años, ha sido afectado por una gran diversidad de plagas, entre las cuales destaca el \"cogollero del maíz\" (*Spodoptera frugiperda*) (Trejo et.al., 2019), considerada una de las más agresivas y dañinas. Esta plaga representa una seria amenaza para la productividad del cultivo, afectando especialmente las etapas iniciales de desarrollo de la planta (Abbas et.al., 2022).Por lo que muchos agricultores han optado por el control químico para combatir al cogollero del maíz. Sin embargo, el uso frecuente e intensivo de insecticidas ha provocado que la plaga desarrolle resistencia. Además, este tipo de control afecta al medio ambiente y a otros insectos beneficiosos (Yao et.al., 2023).

Como alternativa, el control biológico surge como una alternativa de control amigable con el medio ambiente (González-Maldonado et.al., 2015). Siendo una de las técnicas del control biológico usar agentes de biocontrol como entomopatógenos, parasitoides y depredadores (Yao et.al., 2023). En la búsqueda de saber que agentes de biocontrol encontramos en nuestra región nos preguntamos, ¿Qué especies de parasitoides están asociadas a *Spodoptera Frugiperda* en cultivo de maíz (*Zea mays*) en tres pisos altitudinales la región Amazonas, Perú?


